In [2]:

import pickle

for i in range(1, 19):
    file_path = "./log/ ("+  str(i) +").pickle"
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    print(data.keys())

dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])


In [3]:
data['ml'].keys()

dict_keys(['scene_info', 'command'])

In [4]:
data['ml']['scene_info']

[{'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(50, 60),
   (75, 60),
   (100, 60),
   (125, 60),
   (60, 70),
   (85, 70),
   (110, 70),
   (50, 80),
   (75, 80),
   (100, 80),
   (125, 80)],
  'hard_bricks': [(35, 50),
   (60, 50),
   (85, 50),
   (110, 50),
   (135, 50),
   (25, 60),
   (150, 60),
   (35, 70),
   (135, 70),
   (25, 80),
   (150, 80),
   (35, 90),
   (60, 90),
   (85, 90),
   (110, 90),
   (135, 90)]},
 {'frame': 1,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(50, 60),
   (75, 60),
   (100, 60),
   (125, 60),
   (60, 70),
   (85, 70),
   (110, 70),
   (50, 80),
   (75, 80),
   (100, 80),
   (125, 80)],
  'hard_bricks': [(35, 50),
   (60, 50),
   (85, 50),
   (110, 50),
   (135, 50),
   (25, 60),
   (150, 60),
   (35, 70),
   (135, 70),
   (25, 80),
   (150, 80),
   (35, 90),
   (60, 90),
   (85, 90),
   (110, 90),
   (135, 90)]},
 {'frame': 2,
  'status': 'GAME_ALIVE',
  'bal

In [5]:
data['ml']['command']

['SERVE_TO_LEFT',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 None,
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_LEFT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_LEFT',
 'MO

In [6]:
data['ml']['scene_info'][0], data['ml']['command'][-0]

({'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(50, 60),
   (75, 60),
   (100, 60),
   (125, 60),
   (60, 70),
   (85, 70),
   (110, 70),
   (50, 80),
   (75, 80),
   (100, 80),
   (125, 80)],
  'hard_bricks': [(35, 50),
   (60, 50),
   (85, 50),
   (110, 50),
   (135, 50),
   (25, 60),
   (150, 60),
   (35, 70),
   (135, 70),
   (25, 80),
   (150, 80),
   (35, 90),
   (60, 90),
   (85, 90),
   (110, 90),
   (135, 90)]},
 'SERVE_TO_LEFT')

In [7]:
scene_info = data['ml']['scene_info']
command = data['ml']['command']

Ball_x = []
Ball_y = []
Ball_speed_x = []
Ball_speed_y = []
Direction = []
Platform = []
Command = []

for i, s in enumerate(scene_info[1:-2]):
    Ball_x.append(s['ball'][0])
    Ball_y.append(s['ball'][1])
    Platform.append(s['platform'][0])
    Ball_speed_x.append(scene_info[i+2]["ball"][0] - scene_info[i+1]["ball"][0])
    Ball_speed_y.append(scene_info[i+2]["ball"][1] - scene_info[i+1]["ball"][1])
    if Ball_speed_x[-1] > 0:
        if Ball_speed_y[-1] > 0:
            # 右下
            Direction.append(0)
        else:
            # 右上
            Direction.append(1)
    else:
        if Ball_speed_y[-1] > 0:
            # 左下
            Direction.append(2)
        else:
            # 左上
            Direction.append(3)
            
for c in command[1:-2]:
    if c == "NONE":
        Command.append(0)
    elif c == "MOVE_LEFT":
        Command.append(-1)
    elif c == "MOVE_RIGHT":
        Command.append(1)

In [8]:
import numpy as np

numpy_data = np.array([Ball_y, Ball_speed_x, Ball_speed_y, Direction, Platform])
X = np.transpose(numpy_data) 
y = command

In [9]:
X, y

(array([[395,  -7,  -7,   3,  75],
        [388,  -7,  -7,   3,  75],
        [381,  -7,  -7,   3,  75],
        ...,
        [ 28,  10,   7,   0,  70],
        [ 35,  10,   7,   0,  65],
        [ 42,  10,   7,   0,  60]]),
 ['SERVE_TO_LEFT',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  None,
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_LEFT',
  'MOVE_LEFT',
  'MOVE_LEFT',
  'MOVE_LEF

In [10]:
# 提取特徵
import numpy as np

scene_info = data['ml']['scene_info']
command = data['ml']['command']

k = range(1, len(scene_info)-1)

#ball_x = np.array([scene_info[i]['ball'][0] for i in k])
ball_y = np.array([scene_info[i]['ball'][1] for i in k])
ball_speed_x = np.array([scene_info[i+1]['ball'][0] - scene_info[i]['ball'][0] for i in k])
ball_speed_y = np.array([scene_info[i+1]['ball'][1] - scene_info[i]['ball'][1] for i in k])
direction = np.where(np.vstack((ball_speed_x, ball_speed_y)) > 0, [[1],[0]], [[2],[3]]).sum(axis=0)  # x y: ++1, +-4, -+2, --3
platform = np.array([scene_info[i]['platform'][0] for i in k])
target = np.where(np.array(command) == 'NONE', 0,
                  np.where(np.array(command) == 'MOVE_LEFT', -1, 1))[1:-1]  # [0] SERVE_TO_RIGHT, [1897] None


In [11]:
# 也可以使用 pandas
X = np.hstack((#ball_x.reshape(-1, 1),
               ball_y.reshape(-1, 1),
               ball_speed_x.reshape(-1, 1),
               ball_speed_y.reshape(-1, 1),
               direction.reshape(-1, 1),
               platform.reshape(-1, 1)))
y = target

In [12]:
X, y

(array([[395,  -7,  -7,   5,  75],
        [388,  -7,  -7,   5,  75],
        [381,  -7,  -7,   5,  75],
        ...,
        [ 35,  10,   7,   1,  65],
        [ 42,  10,   7,   1,  60],
        [ 49,  10,   6,   1,  55]]),
 array([ 0,  0,  0, ..., -1, -1,  1]))

In [13]:
# train data
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=1)
print(model.fit(X, y))
print(model.score(X, y))

KNeighborsClassifier(n_neighbors=1)
0.9636493228795439


In [14]:
with open('my_model.pickle', 'wb') as f:
    pickle.dump(model, f)