In [27]:

import pickle

for i in range(1, 74):
    file_path = "./log/ ("+  str(i) +").pickle"
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    print(data.keys())

dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys([

In [28]:
data['ml'].keys()

dict_keys(['scene_info', 'command'])

In [29]:
data['ml']['scene_info']

[{'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 {'frame': 1,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 {'frame': 2,
  'status': 'GAME_ALIVE',
  'ball': (86, 388),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 {'frame': 3,
  'status': 'GAME_ALIVE',
  'ball': (79, 381),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 {'frame': 4,
  'status': 'GAME_ALIVE',
  'ball': (72, 374),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 {'frame': 5,
  'status': 'GAME_ALIVE',
  'ball': (65, 367),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (

In [30]:
data['ml']['command']

['SERVE_TO_LEFT',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 

In [31]:
data['ml']['scene_info'][0], data['ml']['command'][-0]

({'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(35, 50), (60, 50), (85, 50), (110, 50), (135, 50)],
  'hard_bricks': []},
 'SERVE_TO_LEFT')

In [32]:
# 提取特徵

scene_info = data['ml']['scene_info']
command = data['ml']['command']

Ball_x = []
Ball_y = []
Ball_speed_x = []
Ball_speed_y = []
Direction = []
Platform = []
Command = []

for i, s in enumerate(scene_info[1:-2]):
    Ball_x.append(s['ball'][0])
    Ball_y.append(s['ball'][1])
    Platform.append(s['platform'][0])
    Ball_speed_x.append(scene_info[i+2]["ball"][0] - scene_info[i+1]["ball"][0])
    Ball_speed_y.append(scene_info[i+2]["ball"][1] - scene_info[i+1]["ball"][1])
    if Ball_speed_x[-1] > 0:
        if Ball_speed_y[-1] > 0:
            # 右下
            Direction.append(0)
        else:
            # 右上
            Direction.append(1)
    else:
        if Ball_speed_y[-1] > 0:
            # 左下
            Direction.append(2)
        else:
            # 左上
            Direction.append(3)
            
for c in command[1:-2]:
    if c == "NONE":
        Command.append(0)
    elif c == "MOVE_LEFT":
        Command.append(-1)
    elif c == "MOVE_RIGHT":
        Command.append(1)

In [33]:
import numpy as np

numpy_data = np.array([Ball_x, Ball_y, Ball_speed_x, Ball_speed_y, Direction, Platform])
X = np.transpose(numpy_data) 
y = command

In [34]:
X, y

(array([[ 93, 395,  -7,  -7,   3,  75],
        [ 86, 388,  -7,  -7,   3,  75],
        [ 79, 381,  -7,  -7,   3,  75],
        ...,
        [ 10,  21,  10,   7,   0,  65],
        [ 20,  28,  10,   7,   0,  60],
        [ 30,  35,  10,   7,   0,  55]]),
 ['SERVE_TO_LEFT',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGH

In [35]:
# 提取特徵
import numpy as np

scene_info = data['ml']['scene_info']
command = data['ml']['command']

k = range(1, len(scene_info)-1)

ball_x = np.array([scene_info[i]['ball'][0] for i in k])
ball_y = np.array([scene_info[i]['ball'][1] for i in k])
ball_speed_x = np.array([scene_info[i+1]['ball'][0] - scene_info[i]['ball'][0] for i in k])
ball_speed_y = np.array([scene_info[i+1]['ball'][1] - scene_info[i]['ball'][1] for i in k])
direction = np.where(np.vstack((ball_speed_x, ball_speed_y)) > 0, [[1],[0]], [[2],[3]]).sum(axis=0)  # x y: ++1, +-4, -+2, --3
platform = np.array([scene_info[i]['platform'][0] for i in k])
target = np.where(np.array(command) == 'NONE', 0,
                  np.where(np.array(command) == 'MOVE_LEFT', -1, 1))[1:-1]  # [0] SERVE_TO_RIGHT, [1897] None


In [36]:
# 也可以使用 pandas
X = np.hstack((ball_x.reshape(-1, 1),
               ball_y.reshape(-1, 1),
               ball_speed_x.reshape(-1, 1),
               ball_speed_y.reshape(-1, 1),
               direction.reshape(-1, 1),
               platform.reshape(-1, 1)))
y = target

In [37]:
X, y

(array([[ 93, 395,  -7,  -7,   5,  75],
        [ 86, 388,  -7,  -7,   5,  75],
        [ 79, 381,  -7,  -7,   5,  75],
        ...,
        [ 20,  28,  10,   7,   1,  60],
        [ 30,  35,  10,   7,   1,  55],
        [ 40,  42,  10,   3,   1,  50]]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1, -1,  1,
        -1,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  

In [38]:
# train data
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=1)
print(model.fit(X, y))
print(model.score(X, y))

KNeighborsClassifier(n_neighbors=1)
1.0


In [39]:
with open('my_model.pickle', 'wb') as f:
    pickle.dump(model, f)